change config

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -16,21 +16,30 @@ jobs:
       uses: actions/checkout@v2
 
     - name: Make deploy.sh executable
-      run: chmod +x ./.github/workflows/deploy.sh
+      run: chmod +x ./deploy.sh
 
     - name: Deploy to server
-      uses: appleboy/ssh-action@master
+      uses: appleboy/ssh-action@v0.1.4
       with:
         host: ${{ secrets.REMOTE_HOST_KEY }}
         username: ${{ secrets.REMOTE_USER_KEY }}
         port: "22"
         key: ${{ secrets.EC2_SSH_KEY }}
         script: |
-          # Navegar até o diretório do projeto
+          set -e  # Termina em caso de erro
+
           cd /www/wwwroot/rpg-back
 
-          # Puxar as últimas atualizações do repositório
+          if ! command -v composer &> /dev/null
+          then
+            echo "Composer não está instalado. Abortando."
+            exit 1
+          fi
+
+          echo "Puxando atualizações..."
           git pull origin main
 
-          # Se estiver usando Composer, instale as dependências com --no-interaction
+          echo "Instalando dependências..."
           composer install --no-dev --optimize-autoloader --no-interaction
+
+          echo "Deploy concluído com sucesso!"
